- name: Update and upgrade all packages to the latest version
  apt:
    update_cache: yes
    upgrade: dist
    state: latest

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - software-properties-common
      - git
      - python3-setuptools
      - virtualenv
      - python3-pip
    state: latest

- name: Create directory for Docker's GPG key
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker's official GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository to apt sources
  copy:
    content: |
      deb [arch={{ arch_mapping[ansible_architecture] }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    dest: /etc/apt/sources.list.d/docker.list
    
- name: Install Docker CE
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin 

- name: Copiar el archivo docker-compose.yml al servidor
  template:
    src: ../templates/docker-compose.yml.j2
    dest: /home/ubuntu/docker-compose.yml
    mode: '0644'

- name: Ejecutar docker-compose up para levantar los servicios
  shell: docker compose -f /home/ubuntu/docker-compose.yml up -d
  
- name: Manejar actualizaciones y reinicios de los servicios 
  shell: docker compose -f /home/ubuntu/docker-compose.yml restart
