- name: Ejectuar problemas
  hosts: all
  become: yes
  become_method: sudo
  remote_user: vagrant
  vars_files:
    - ansible/vars.yml
  # Estas variables nos serán util para la instalación de docker  
  vars:
    arch_mapping:  
      x86_64: amd64
      aarch64: arm64
  tasks:
    #- import_tasks:  ansible/ejercicio1/main.yml
    #- import_tasks:  ansible/ejercicio2/main.yml
    #- import_tasks:  ansible/ejercicio3/main.yml
    #- import_tasks:  ansible/ejercicio4/main.yml
    - import_tasks:  ansible/ejercicio5/main.yml
    #- import_tasks:  ansible/ejercicio6/main.yml
    #- import_tasks:  ansible/ejercicio7/main.yml
    #- import_tasks:  ansible/ejercicio8/main.yml
    #- import_tasks:  ansible/ejercicio9/main.yml
    #- import_tasks:  ansible/ejercicio10/main.yml
  handlers:
    - import_tasks: handlers/restart_prometheus.yml
    - import_tasks: handlers/restart_app.yml
    - import_tasks: handlers/restart_ufw.yml
    - import_tasks: handlers/restart_systemd.yml
    - import_tasks: handlers/restart_lynis.yml
    - import_tasks: handlers/restart_nginx.yml
    - import_tasks: handlers/restart_ssh.yml
