- name: Update and upgrade all packages to the latest version
  apt:
    update_cache: yes
    upgrade: dist
    state: latest

- name: Install required packages
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg
      - software-properties-common
      - git
      - python3-setuptools
      - virtualenv
      - python3-pip
    state: latest

- name: Create directory for Docker's GPG key
  file:
    path: /etc/apt/keyrings
    state: directory
    mode: '0755'

- name: Add Docker's official GPG key
  get_url:
    url: https://download.docker.com/linux/ubuntu/gpg
    dest: /etc/apt/keyrings/docker.asc
    mode: '0644'

- name: Add Docker repository to apt sources
  copy:
    content: |
      deb [arch={{ arch_mapping[ansible_architecture] }} signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/ubuntu {{ ansible_distribution_release }} stable
    dest: /etc/apt/sources.list.d/docker.list
    
- name: Install Docker CE
  apt:
    name: "{{ item }}"
    state: latest
    update_cache: yes
  loop:
    - docker-ce
    - docker-ce-cli
    - containerd.io
    - docker-buildx-plugin
    - docker-compose-plugin 

- name: Copiar el Dockerfile.ejercicio8 al servidor
  template:
    src: ../docker/Dockerfile.ejercicio8
    dest: /home/ubuntu/Dockerfile
    mode: '0644'

- name: Copiar app.py
  template:
    src: app.py
    dest: /home/ubuntu/app.py
    mode: '0644'

- name: Copiar los requirements
  template:
    src: requirements.txt
    dest: /home/ubuntu/requirements.txt
    mode: '0644'

- name: Construir imagen
  docker_image:
    name: flask_app_image
    build:
      path: /home/ubuntu
    state: present
    source: build
    
- name: Levantar contenedor
  docker_container:
    name: flask_app
    image: flask_app_image  
    state: started
    restart_policy: always
    ports:
      - "5000:5000"